# Generated by Django 4.2.5 on 2023-09-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_portfolio_project_student_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
