# Generated by Django 4.2.5 on 2023-09-30 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_alter_portfolio_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='portfolio',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.portfolio'),
        ),
    ]
