# Generated by Django 4.2.5 on 2023-09-30 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0007_projectsinportfolio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectsinportfolio',
            unique_together={('portfolio', 'project')},
        ),
    ]
