# Generated by Django 4.2.5 on 2023-10-17 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0008_alter_projectsinportfolio_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectsInPortfolio',
        ),
    ]
